### ISSUE TITLE
TeX Live 収録

### ISSUE THREAD

**Issue by kmaed** [texjporg/platex#1]
TeX Live への収録にあたって，更新作業をしています．以下，uplatex と共通です．

- Karlさんからの提案により，パッケージ（リポジトリ）名 platex-base を platex に変更しました．ptex-base などと違って対応するバイナリがないので -base を外しても衝突しないだろう，TeX Live での管理の都合上シンプルに platex の方がよいという理由です．お手数ですがリポジトリが手元にある方は clone し直して下さい．
- TeX Live の更新作業が英語環境で行われるため，できれば .tds.zip があった方が不安がなくてよいということなので，自動生成スクリプトを書きました．

あと，[(u)platex.ini の件](https://github.com/texjporg/ptex-texmf/issues/9)はどうしましょうか．

(u)platex.pdf 内の URL も変更したので，お手数ですがヒラギノフォントをお持ちの方は生成しなおしていただけると助かります．

**Comment by aminophen** [comment]
.tds.zip ができるのは便利です！ ありがとうございます。(u)platex.ini は進める方向でよいと思います。私の理解が追いついていないかもしれないのでメモさせてください：

そのコードが必要とされたそもそもの経緯は

- [qa:37405](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/37405.html) の問題があるので [qa:31691](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/31691.html) の方法が採用された。
- これには [qa:31723](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/31723.html) の注意を要するが、今のところ大きな問題は起きていない。
- ただし [qa:44444](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/44444.html) にあるように、hyphen.cfg がいちいち更新されないといけない。
- そこで、これを (u)platex.ini に入れてしまおう → 今に至る

(u)platex.pdf は私より早い方がいらっしゃらなければ明日中に再生成しておきます。

**Comment by munepi** [comment]
@kmaed @aminophen さん＞.tds.zip が生成できているの、よいですね！
さきほど (u)platex.pdf をこちらの手元で再生成いたしましたので、確認いただけますでしょうか。

**Comment by kmaed** [comment]
> さきほど (u)platex.pdf をこちらの手元で再生成いたしましたので、確認いただけますでしょうか。

ありがとうございます．HiraginoSansPr6N-W3 ですか．W6 じゃないのですが，これでよいのかな？

(u)platex.ini については，今NorbertさんがKarlさんに意見を聞いているようです．

**Comment by munepi** [comment]
> HiraginoSansPr6N-W3 ですか．W6 じゃないのですが，これでよいのかな？

なるほど、手元の設定でビルドしていました。HiraginoSansPr6N-W3 -> W6に変えて、再度 (u)platex.pdf を push しました。
