### ISSUE TITLE
algorithm2e と ascmac の衝突

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#15]
algorithm2e → ascmac の順に読み込むと、`\Return` が上書きされて変になります。ascmac が `\def` を使っているが故に起きる意図しない挙動の例として挙げます。

``` tex
\documentclass{jarticle}
\usepackage{algorithm2e}
\usepackage{ascmac}
\begin{document}

\begin{algorithm}
\SetAlgoLined
\lIf{cond5}{cond5 true}
\uElseIf{cond51}{
  cond5 false\;
  but cond51 true\;
}
\ElseIf{}{
  all is wrong\;
  \Return result52\;
}
\end{algorithm}

\end{document}
```

**Comment by aminophen** [comment]
あまり綺麗ではありませんが、tascmac.sty で「大文字で始まる \Return」だけ \newcommand にしようかと考えています。

＃ 本来なら小文字の \return も \newcommand にしたい（というか本来ならばそうするべき）ですが、okumacro.sty に同名で違う出力の \return という命令があるのがネックになっています。「okumacro → ascmac の順で読み込むと（重複する命令名は \def で上書きするため）エラーが出なくて、両方利用可能」というバッドノウハウはよく使われていたようなので、これが壊れると困る人が出そうです。

**Comment by aminophen** [comment]
41e5e69 で `\Return` だけ上書きが起きないようにしました（`\return` は未チェック）。

「`\Return` 命令が定義されていて，かつその中身に `\@ascgrp` が登場していない場合」にはエラーが発生するようになっています。アドホックすぎる感はありますが，

- ascmac は「screen とか boxnote とか枠を作るパッケージ」として知られているケースが多い。
- 一方で，ascmac の `\Return` のような雑マクロはそれほど知られていないと思われる。
- 結果的に，「問題が起きても原因に気付かない」状況が生じやすい。

という可能性はあるので，入れておくことにします。

**Comment by zr-tex8r** [comment]
```tex
\edef\ASCGRP{\string\@ascgrp}
```

で済む、感じがする。
というか、`\ASCGRP` の代わりに `\string\@ascgrp` で十分かも。

**Comment by aminophen** [comment]
確かに簡単でした… ご指摘ありがとうございました。(6048a0f)

**Comment by aminophen** [comment]
確かに簡単でした… ご指摘ありがとうございました。(9ea3098)

**Comment by aminophen** [comment]
Closed via release 2017-07-29.
