### ISSUE TITLE
縦数式ディレクションとベースライン補正

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#22]
pLaTeX の Issue に書くのは違っているような気がしますが、Forum よりはこちらのほうが適していそうなので、ここに書きます。

以下のソースで、TeX Live 2015 と TeX Live 2016 の pLaTeX の挙動が違います。2016 の出力を 2015 と同じにしようとすると、2箇所付けているコメントのうち**一方だけ**を有効にする必要があります。

``` tex
%\textbaselineshiftfactor0        % この行か、または…
\documentclass{tarticle}
\begin{document}
%\ybaselineshift\tbaselineshift   % この行を有効にする
\[
|x| = \left\{ \begin{array}{rl}
 -x &\mbox{ if $x<0$} \\
  x &\mbox{ otherwise}
       \end{array} \right.
\]
\end{document}
```

変化した理由は [forum:1851](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1851) でしょう。横組だとこういうソースの書き方をよく見かけますが、縦組ではどう書くのが好ましいのでしょうか。

**Comment by h-kitagawa** [comment]
次の「テスト1」で A と a の垂直位置がずれているのと同じ理由と思われます．
```tex
テスト1: $A\hbox{aあいう}$\par
テスト2: $A\hbox{\tate aあいう}$
```
テスト1の `\hbox` は縦数式ディレクションなので，小文字の a は `\ybaselineshift` だけ下がります．
しかし `\textbaselineshiftfactor` が 1000 なので，そこから `\tbaselineshift` だけ上がってしまうことになります．
一方，テスト2では `\hbox` は通常の縦ディレクションなので，小文字の a は `\tbaselineshift` だけ下がり，また同じ量だけ上がるので，大文字の A と同じ垂直位置になります．

ボックスが通常の縦ディレクションで組まれているのか，それとも縦数式ディレクションで組まれているのかを判断できればよいのですが，現在の pTeX では一旦ノードとして組まれてしまうとその情報は失われてしまいます．

**Comment by aminophen** [comment]
なるほど、テスト2のように \tate を明示して通常の縦ディレクションに入れればよいのですね。現在の pTeX ではボックスの縦ディレクションと縦数式ディレクションを区別できない、というのも、言われてみればそうでした。書くときに注意するしかなさそうですね…。ありがとうございます。

**Comment by aminophen** [comment]
TeX Live [r42040](http://www.tug.org/svn/texlive?view=revision&revision=42040), [r42041](http://www.tug.org/svn/texlive?view=revision&revision=42041) のパッチ確認しました。良い仕様だと思います。
