### ISSUE TITLE
電子情報通信学会のテンプレートでレイアウトが乱れる

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#23]
電子情報通信学会のテンプレートが、2016/09/03 の pLaTeX2e でレイアウトが乱れるという報告を頂きました。これの template.tex をコンパイルすると、SUMMARY の上に妙なスペースが入ります。

- http://www.ieice.org/ftp/tex/ieice/LaTeX2e/ieice2.2.zip （zip 直リンク）

~~~~ tex
\RequirePackage[2016/09/02]{platexrelease}
~~~~
を付けると直るので pLaTeX 側の問題である可能性もある。

**Comment by aminophen** [comment]
原因は `\@footnotetext` の定義を変えたこと、なのまではわかったのですが、なぜレイアウトが変わるのかよくわかりません…（ieice.cls をみると \protect\footnotetext なるコードが多数出てくるのですが、`\@footnotetext` が直書きされている場所は見当たりません。）

**Comment by munepi** [comment]
以下の例で、ieice.cls 以外の jclasses や jsclasses でもこれが再現できますね。

```
%#!ptex2pdf -l -u
\documentclass{ujarticle}
\begin{document}
\footnotetext{あああああ}%
\footnotetext{あああああ}%
\footnotetext{あああああ}%
\footnotetext{あああああ}%
\footnotetext{あああああ}%
\footnotetext{あああああ}%

あああああ
\end{document}
```

**Comment by h-kitagawa** [comment]
`\@footnotetext` の定義中の
```tex
    \color@begingroup
      \@makefntext{%
        \rule\z@\footnotesep\ignorespaces#1\@finalstrut\strutbox}%
    \color@endgroup}\null
```
で，`\null` が悪さをしているかもしれません．
```tex
\ifhmode\null\fi
```
としてはどうなるでしょうか？

**Comment by aminophen** [comment]
> \ifhmode\null\fi

ああ、そうでした。[この前の lshort.tex で \unpenalty は \ifhmode ... \fi にしないといけないという話](https://github.com/texjporg/platex/issues/16#issuecomment-243173891)のときにもう少しいろいろ試すべきでした… 速攻で platex / uplatex / jsclasses を修正してリリースします。

**Comment by aminophen** [comment]
作業完了しました。2日以内に TeX Live に入って、3日後ごろミラーに下りてくると思います。それまではお手数ですが \RequirePackage[2016/09/02]{platexrelease} で乗り切ってください。
