### ISSUE TITLE
「…」の後の全角スペース

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#29]
[Twitter で拾いました](https://twitter.com/quinoppie/status/805491589313200128)。「…」のあとに全角スペースを置いたときの挙動です。

~~~~ tex
\documentclass{jsarticle}
\parindent=0pt
\textwidth=20zw
\begin{document}
あいうえおかきくけこさしすせそたちつてとあいうえおかきくけこ\par
あいうえおかきくけこさしすせそたちつて？　あいうえおかきくけこ\par
あいうえおかきくけこさしすせそたちつて！　あいうえおかきくけこ\par
あいうえおかきくけこさしすせそたちつて…　あいうえおかきくけこ\par
\end{document}
~~~~

このソースで「？」や「！」や「…」のあとの全角スペースが行頭に来ます（jsarticle でも jarticle でも同じ）。私は違和感を感じるのですが、これはこのほうがよいのでしょうか？

**Comment by yuw** [comment]
> \parindent=0pt
> \textwidth=20zw
なので，21文字目の全角スペースが次行行頭にくるのは自然で，入力された通りの挙動にみえます．

**Comment by aminophen** [comment]
「入力された通りの挙動」なのは確かなのですが、入力した人が本当に得たいものとは違うような気がする、ということです。全角空白が消滅してほしいのではないかと思ったので。

**Comment by aminophen** [comment]
（もちろん、入力の仕方が悪い、といってしまえばそれまでなのですが。）
