### ISSUE TITLE
plext の \@Kanji

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#33]
[abenori さんから](https://twitter.com/abenori/status/756169880429223936)です。

漢数字をラベルに使った二段階の enumerate を定義すると

~~~~ tex
\documentclass{tarticle}
\renewcommand{\theenumi}{\Kanji{enumi}}
\begin{document}

\begin{enumerate}
\item ほげ
\begin{enumerate}
\item ふが
\end{enumerate}
\end{enumerate}

\end{document}
~~~~

がエラーになります。

~~~~
! Use of \@item doesn't match its definition.
\@ifnextchar ... \reserved@d =#1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.8 \item ふ
            が
~~~~

もっと簡単な例だと

~~~~ tex
\documentclass{article}
\usepackage{plext}
\begin{document}
\section{test}
\Kanji{section}6は
\end{document}
~~~~

などで、引数でない後続の 6 まで漢数字になります。

~~~~ tex
\def\@Kanji#1{\expandafter\kansuji\number #1}
~~~~

の最後の `#1` の後に \relax または半角スペースを足せばよいようです。

（ついでにいうと plext.dtx の \Alpha は \Alph のタイポですね。）

**Comment by aminophen** [comment]
\relax を足す方法だと、先日の #31 のときのように目次で後ろの空白が喰われるみたいです。半角スペースの方だと喰われないのでそちらの方がいいのかな？と考え中です。

**Comment by aminophen** [comment]
ためしに半角スペースを足してみました。（明らかにバグなので master ブランチ。）

~~~~ tex
\def\@Kanji#1{\expandafter\kansuji\number #1 }
~~~~

**Comment by wtsnjp** [comment]
TeX 言語の `<number>`（より正確には `integer denotation`）は `<one optional space>` を取れるので半角スペースを入れても構わないはずです．

**Comment by wtsnjp** [comment]
しかし，疑問なのはそもそもなぜ `\@Kanji` が `\number` を噛ませる実装になっているかです．少なくとも plext.sty 内では `\@Kanji` は `\Kanji` 内でしか用いられておらず，必ず `\c@<foo>` というカウンタレジスタを引数として受け取るので `\number` を噛ませる必要はありません．

`\@roman` は latex.ltx 内でシンプルに

```
\def\@roman{\romannumeral #1}
```

と実装されています．これに倣うのであれば `\@Kanji` も

```
\def\@Kanji{\kansuji #1}
```

で十分なはずです．

**Comment by aminophen** [comment]
> TeX 言語の <number>（より正確には <integer denotation>）は <one optional space> を取れるので半角スペースを入れても構わないはずです．

ありがとうございます。私も同じ考えです。

> 疑問なのはそもそもなぜ \@Kanji が \number を噛ませる実装になっているかです．

私もこれは疑問を持っています。一つの可能性としては \kansuji が[プリミティブから外された時期があった]()https://www.ma.ns.tcu.ac.jp/Pages/TeX/metakansuji.html ことです。今でこそ \kansuji は \romannumeral と \number と同様の「整数を文字列に変換するプリミティブ」ですが、そうでなかった時期に \number が必要だったのでは…というあくまで推測です。

**Comment by aminophen** [comment]
もし上記が正しいならば、プリミティブとして定着してから既に十年以上たっていることを加味して `\@roman` に倣ったシンプルな定義の方がよいという主張は妥当で、好ましいという気もします。他の方々からも別の理由が出ないようであれば変更しましょう。

**Comment by aminophen** [comment]
> `\@roman` に倣ったシンプルな定義

6166151 でシンプルな定義に変更しました。テストケース tests/plext_kanji.tex も問題ありません。
