### ISSUE TITLE
Windows, Linux, macOSによるCIの追加

### ISSUE THREAD

**Issue by y-yu** [texjporg/platex#34]
前回 #19 にてCIの追加は結局行われなかったわけですが、今回は私の方でWindowsによるCIについても実行する目処を立てました。もし、Windows, Linux, macOSの3つでコンパイルしてみるようなCIであればどうでしょうか。 #19 は結局マージされずに終ってしまったので、作業をはじめる前に、開発者の方々の意見を伺いたいと思います。

よろしくおねがいします。

**Comment by aminophen** [comment]
ありがとうございます。

> Windows, Linux, macOSの3つでコンパイルしてみるようなCIで

CI で実行するのは具体的にどの行程でしょうか？「pldoc.pdf などのドキュメント pdf のビルド and/or デプロイ」なのか、「pLaTeX の組版結果が妥当かどうかのテスト」なのかです。

**Comment by y-yu** [comment]
私は、pldoc.pdfなどのドキュメントのビルドとデプロイを考えています。

**Comment by aminophen** [comment]
知識がなくてすみませんが、「Windows な CI」には GNU make や sh はインストールされているのでしょうか？

**Comment by aminophen** [comment]
> ドキュメントのビルド

改めてですが、私はドキュメントのビルドを重視していません。「Windows / Mac / Linux でコンパイルが通るかどうか」みたいな話が意味を持つのは、たとえば C 言語のソースのコンパイルとかだと思います。Windows の Visual C とか Mac の clang とか Linux の gcc とかを想定して、「異なる C 言語コンパイラで同じ hoge.c がコンパイルできる」だと意味がありますが、そうでなく「全部 platex という同じコンパイラでコンパイルする」という本リポジトリの場合は意義が薄いです。

CI という仕組みが便利なのは認めますが、pldoc.pdf 等のドキュメントだけに限ると CI の出る幕は少ないです。私が CI で実現したいのは、latex3 が採用している「テストの自動化」です。[latex3 リポジトリの travis 設定](https://github.com/latex3/latex3/blob/master/.travis.yml)を参照していただけるとよいですが、こういうものを作りたいです。これは Linux の仮想環境だけを使っていますが、「latex というコンパイラでコンパイルした結果が正常かどうか」をテストするには十分です。現在 platex リポジトリでこれをやっていないのは、tests/ ディレクトリのファイル数が少なすぎるからです。これを増やす作業を私は手元でこっそり進めてはいますが、まだまともではありません。

**Comment by y-yu** [comment]
たびたび失礼しました。どうやら必要ないようですので、このissueはクローズします。
