### ISSUE TITLE
トンボの時刻

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#36]
トンボに日付を出力する tombow オプションを試していて、午前 3 時 2 分に処理したところ 2017/2/18(3:2) と出てきました。時刻が一ケタの数字で表されるときでも、3:「2」というのは奇妙な気がするのですが、3:02 あるいは 03:02 と出すように、jclasses の仕様を変えたらまずいでしょうか？ jsclasses がやっているのと同様に `\two@digits` をかませればよいと思うのですが。

~~~~ tex
\documentclass[a5paper,tombow]{jarticle}
\begin{document}
トンボのテストです。
\end{document}
~~~~

**Comment by munepi** [comment]
> jsclasses がやっているのと同様に \two@digits をかませればよいと思うのですが。

+1 します。

本件は些細なことですが、気になりますよね。

**Comment by aminophen** [comment]
ありがとうございます。

ちなみに最初のだと「3:02 あるいは 03:02 と出すように」と曖昧でしたので、補足させていただきます。

jsclasses は
`2017-02-18 03:02`
の桁数固定書式ですが、jclasses は
`2017/2/18(3:2)`
という書式になっています。年月日のところは jclasses は桁数が成り行きですが、奇妙とはいえないので現状維持でいいんじゃないかと思います。時分のところが問題ですが

`testfile 2017/2/18(03:02)` ← 時も分も二桁固定

`testfile 2017/2/18(3:02)` ← 時は成り行き、分だけ二桁固定

を並べてみると、時のほうは年月日との兼ね合いで成り行きのままとしたほうが個人的に自然に見えたので、分だけ二桁固定にするという提案に固めます。

**Comment by wtsnjp** [comment]
どのみち**後方互換性を破壊する変更を行うのであれば**，個人の感覚に任せた仕様にするよりも何らかの標準的な書式（例えば [ISO8601](https://ja.wikipedia.org/wiki/ISO_8601)）に合わせる方がいいような気がします．

**Comment by aminophen** [comment]
> どのみち後方互換性を破壊する変更を行うのであれば，個人の感覚に任せた仕様にするよりも何らかの標準的な書式（例えば ISO8601）に合わせる方がいいような気がします．

これは私も頭をよぎったのですが、実際のところどうするのがよいでしょう？

ISO8601 の実装例を見ていると、タイムゾーンを表す `+09:00` あるいは `Z` を入れた例ばかりが出てきます。また、秒まで表示する例が多いようにも見受けられます。しかし、どちらも素の pTeX では不可能ですから、e-pTeX の拡張機能を使うのだと思いますが、[クラスファイルに関しては古い環境に持っていく可能性も考慮したほうがよい](https://github.com/texjporg/jsclasses/issues/49)という話もありました。中途半端に合わせにいくよりは、独自仕様のほうが混同を避けられるという考え方もアリだと思います。

**Comment by wtsnjp** [comment]
ISO8601 本体が手に入っていないので，できれば識者から情報をいただきたいですが，私が調べた限り

* 日付は `YYYYMMDD`（[[70]](https://wiki.suikawiki.org/n/JIS%20X%200301%3A2002$208#anchor-70)）
* 分は精度を削減した `hhmm`（[[75]](https://wiki.suikawiki.org/n/JIS%20X%200301%3A2002$208#anchor-75)）
* 時間帯指示子には空文字列が認められている（[[90]](https://wiki.suikawiki.org/n/JIS%20X%200301%3A2002$208#anchor-90)）
* 時刻指示子は曖昧でなければ省略可（[[91]](https://wiki.suikawiki.org/n/JIS%20X%200301%3A2002$208#anchor-91)）

らしいので，例えば `YYYYMMDDhhmm` や `YYYY-MM-DDThh:mm` などが認められるという認識をしています．

**Comment by aminophen** [comment]
Adobe InDesign でトンボを出してページ情報を表示させると、右下に 2017/02/18 15:02:04 のような書式で出てくるという情報を頂きました。出版の世界では ISO に従うよりアスキーのようなスラッシュの方が主流なのでしょうか？ この辺は私は判りません。

**Comment by aminophen** [comment]
悩みましたが、「分」だけを二桁固定にする案で通そうかと思っています。ISO に準拠したものが実用サイドから要求されているわけではないので、「見た目が奇妙でないようにする」というマイナーチェンジにとどめるという意図です。もうしばらくご意見を待ったうえで commit します。

**Comment by yuw** [comment]
> 「分」だけを二桁固定にする案

一つだけ固定というのは奇妙に感じます．ISO式にするか，どれも桁数を固定しないかでしょう．
私はISO式にする方がよいと思っていますし，自分でクラスファイルを作成するときは特に必要がなければそのようにしています．これによって日時による文字列長の変化が抑制できます．

**Comment by aminophen** [comment]
アスキーの意図がどこにあるのか判らないので極力変えない方がよいかと思いましたが、変えたいという意見が多いのであればそういたします。具体的な書式はどうするのがよいでしょう。

文字列長が変わらないようにというのも色々考えられます。

- ISO に従う `YYYYMMDDhhmm`
- ISO に従う `YYYY-MM-DDThh:mm`
- jsclasses と同じ `YYYY-MM-DD hh:mm` （ISO に従うかどうか微妙？）
- 日付をスラッシュのままにする場合 `YYYY/MM/DD hh:mm` （ISO には準拠しない）
- 現在のアスキー版に最も近い `YYYY/MM/DD (hh:mm)` （ISO には準拠しない）

具体的にどれを実装するのがよいでしょうか？

**Comment by wtsnjp** [comment]
> * jsclasses と同じ YYYY-MM-DD hh:mm （ISO に従うかどうか微妙？）

おそらく ISO に準拠しないです．

前にも引用した[文献](https://wiki.suikawiki.org/n/JIS%20X%200301%3A2002$208#anchor-176)に以下のような一般的注意が書かれています．

> しかし、いつでもどこでもむやみに ISO 8601 の日時形式を採用するべきとも言えません。 例えば ISO 8601 の規定に従えば日付と時刻の間には「T」と記載することになります (例えば2016年3月25日の12時18分は 2016-03-25T12:18 と表記します。) が、 人間が対象読者なら、この表記は一般的ではありませんから、奇妙に思われるでしょう。 時刻を「time」と呼ぶ英語圏ですら、この表記は (人間対象には) 普及していません。

したがって，まず最初に考えるべき方針としては

* トンボの時刻は人間が見ることを主目的とする → ISO に準拠しない方がよい
* トンボの時刻は計算機で扱うことを主目的とする → ISO に準拠した方がよい

かなと思います．

**Comment by aminophen** [comment]
> したがって，まず最初に考えるべき方針としては

確かにそうですね。

素人のコメントで申しわけないですが、InDesign のトンボのジョブ情報などから推察するに、人間が読めればよいのだと思います。トンボの場所も pLaTeX クラスでは左上ですが、InDesign は右下、[これ](https://affinity-tips.com/affinity-designer/affinity-designer-basic/how-to-make-crop-marks)などは右上に出ていますし、機械が読んでいるならばもう少し統一されたガイドラインがありそうな気がします。

というわけで「トンボの時刻は人間が見ることを主目的とする → ISO に準拠しない方がよい」

- jsclasses と同じ YYYY-MM-DD hh:mm
- InDesign に近い YYYY/MM/DD hh:mm
- 現在のアスキー版に最も近い YYYY/MM/DD (hh:mm)

が残ります。

（「ISO に準拠しないけれども文字列長を固定しない」という選択肢がないとはいえませんが、固定すべきという意見が多そうなので今回は排除してよいということでよいですね？）

**Comment by aminophen** [comment]
jsclasses と同じ書式にそろえる（ISO に準拠しないが、桁数は固定）、でよいですかね？

jobname (2017-03-02 03:35)

のようになります。異論なければこれにします。

**Comment by aminophen** [comment]
6645879 でトンボの日付を jsclasses の書式に変更しました。
