### ISSUE TITLE
アクセント付き文字前後の \xkanjiskip

### ISSUE THREAD

**Issue by h-kitagawa** [texjporg/platex#5]
早速 ZR さんが 「pLaTeX が新しくなってアレ」(http://d.hatena.ne.jp/zrbabbler/20160606/1465165011) で，Å だけでなく é, ê のような全てのアクセント合成を行っている文字について
周囲に \xkanjiskip が入らなくなる問題を指摘されています．

2つほどパッと思いつく方法を考えていますが，どちらも次のようにうまくいかず，悩んでいます．
- \lower\box ではなく \unhbox にする→ベースライン補正が効かなくなる
- アクセントの前の文字や，アクセントのつく「本体」の文字の符号位置を \lastnodechar で取得し，必要なら \xkanjiskip を挿入する→「前」はなんとかなるが，「後」が問題．OT1 には欧文ゴーストはなさそう．

**Comment by h-kitagawa** [comment]
af4035781377972774c8a72e54ac24105cc7ca57 で部分的に対応しました．
 * \'e, \^e など \DeclareTextComposite[Command] を使わないで出力している場合は前後に \xkanjiskip が入るはずです．
 * \AA のように \DeclareTextComposite[Command] で定義された場合は，後ろに \xkanjiskip ははいりません．（前は \lastnodechar で適当に入れています）

**Comment by zr-tex8r** [comment]
実は今の実装にはもう1つ大きな問題があります。それは、
`\begingroup` などを使っているため、完全展開可能であるべき場合にそうならず、
結果的にカーニング・リガチャが阻害される
というものです。
例えば、T1エンコーディングにおいては、`\'e` は `^^e9`（文字トークン）に
完全展開される必要があります。

**Comment by zr-tex8r** [comment]
ちなみに自分は次のような戦略を立てていました。

  * `\\ENC\x-y` が未定義 → `\ENC\x{y}` （旧実装通り）
  * `\ｱﾚbaselineshift` がゼロ → `\\ENC\x-y` （旧実装通り）  
    ※OT1の`\'e`はこのケースになる
  * `\\ENC\x-y` の意味が単一の文字トークンである → `\\ENC\x-y` （完全展開可能を保持）
    ※T1の`\'e`はこのケースになる
  * それ以外 → `\ｱﾚbaselineshift` の対策をする。完全展開可能は不要。  
    ※ここでは `\xkanjiskip` が落ちても仕方が無い  
    ※OT1の`\r{A}`（=`\AA`）はこのケースになる

※場合分けは展開限定で実装する。

**Comment by zr-tex8r** [comment]
（直接関係しない話ですが）

コレってよく知られている性質なんですかね？

```tex
% plain pTeX
\ybaselineshift=2pt % ゼロでも同様の結果
あ{\accent19 e}あ % 両側に \xkanjiskip が入る
\par
あ\hbox{\accent19 e}あ % 右側だけ \xkanjiskip が入る
\bye
```

**Comment by h-kitagawa** [comment]
「`\\ENC\x-y` の意味が単一の文字トークンである」の判定に自信がありませんが，e83377e59fac7c274bbbb7b8a505f6d47397c9e1 で似たような戦略を書いてみました．
（`\ｱﾚbaselineshift` が 0 の場合はボックスを `\unhbox` することで対応）

**Comment by h-kitagawa** [comment]
少なくとも私は知りませんでした．> `あ\hbox{\accent19 e}あ`
あとでパッチを書きます．

**Comment by aminophen** [comment]
> `>  あ\hbox{\accent19 e}あ`

ほんとですね、知りませんでした。パッチありがとうございます。

本題の e83377e のほうもよさそうに見えます。この修正は早めに CTAN に出した方がよさそうですね。

**Comment by zr-tex8r** [comment]
「`\ｱﾚbaselineshift` を効かせて出力する」の部分なんですが、
「数式中の明示hbox」の仕様を利用する、という手はないですかね。
ちゃんと検討していないのですが、チョット試した感じだと `\xkanjiskip` が落ちないように見えます。

```latex
\documentclass{jsarticle}
\usepackage{plext}
\begin{document}

\newbox\CharBox
\def\MakeCharBox#1{\setbox\CharBox\hbox{%
    \ybaselineshift=0pt \tbaselineshift=0pt #1}}
\def\UseCharBox{$\textbaselineshiftfactor=0 \box\CharBox$}

\ybaselineshift=5pt
あAあ\par
\MakeCharBox{\AA}あ\UseCharBox あ\par

\parbox<t>{6zw}{%
  \ybaselineshift=15pt \tbaselineshift=15pt
  あAあ\par
  \MakeCharBox{\AA}あ\UseCharBox あ\par}

\parbox<t>{6zw}{%
  \ybaselineshift=15pt \tbaselineshift=15pt
  $\hbox{あAあ}$\par
  $\MakeCharBox{\AA}\hbox{あ\UseCharBox あ}$\par}

\end{document}
```

**Comment by zr-tex8r** [comment]
> この修正は早めに CTAN に出した方がよさそうですね。

らしいので、取りあえず早めにCTANに出しましょうか。
ただ、明らかに直した方がよさそうな箇所にコメント入れました。 ＞ e83377e

**Comment by aminophen** [comment]
e83377e のコメント部分は修正いただいたので、uplatex を platex と sync しておきました。それぞれ pLaTeX 2016/06/07 と pLaTeX 2016/06/07u01 になります。

> 「`\ｱﾚbaselineshift` を効かせて出力する」の部分なんですが、
> 「数式中の明示hbox」の仕様を利用する、という手はないですかね。

これおもしろい ;)  Pull request 歓迎します。

**Comment by h-kitagawa** [comment]
> 「\ｱﾚbaselineshift を効かせて出力する」の部分なんですが、
> 「数式中の明示hbox」の仕様を利用する、という手はないですかね。

いいですね．中身の `\xspcode` の値で前後に `\null` を補ったりすれば，
`\xspcode` が 3（前後とも許可）以外の場合に対応できそうですし．

**Comment by kmaed** [comment]
> それぞれ pLaTeX 2016/06/07 と pLaTeX 2016/06/07u01 になります。

どのタイミングで CTAN に出せばよいでしょうか？ 一旦これで OK なのか，さらに直すのか．

**Comment by aminophen** [comment]
では、日本時間の今日 (6/7) 中に CTAN へ出すことを目標にしましょう。間に合うならさらに直したものが better ですね。Markdown の Pull request #4 も merge したいです。

**Comment by aminophen** [comment]
plfonts.dtx l.1688 は、要するに `#2` でよさそうです。
~~~~ tex
    \@secondoftwo#1{#2}%
~~~~

**Comment by aminophen** [comment]
今の実装だと \xkanjiskip が OT1 だと入るのに T1 だと入らないことに気づきました。どこか勘違いしているでしょうか？（「`\\ENC\x-y` の意味が単一の文字トークンである」の実装が正しくない？）
~~~~ tex
\RequirePackage[2016/06/07]{platexrelease}
\documentclass{jarticle}
\usepackage[T1]{fontenc} % これをコメントアウトすると OT1
\usepackage{lmodern}
\begin{document}
あ\`eあ
\end{document}
~~~~

**Comment by h-kitagawa** [comment]
デフォルトだと 128--255 の `\xspcode` は 0 となっており，前後の `\xkanjiskip` の挿入が許可されていないからです．次のように 3 に設定するとちゃんと動くはず．
```tex
\RequirePackage[2016/06/07]{platexrelease}
\documentclass{jarticle}
\usepackage[T1]{fontenc} % これをコメントアウトすると OT1
\makeatletter
\@tempcnta="80
\loop\ifnum\@tempcnta<\@cclvi
  \xspcode\@tempcnta=3
  \advance\@tempcnta\@ne
\repeat
\usepackage{lmodern}
\begin{document}
あ\`eあ
\end{document}
```

**Comment by aminophen** [comment]
> デフォルトだと 128--155 の `\xspcode` は

理解しました。この範囲の禁則パラメータは jsclasses では最適化されていて、標準クラスはデフォルトのままだったのを思い出しました。pLaTeX に取りこんではならないのでしょうか？

**Comment by h-kitagawa** [comment]
> 禁則パラメータ 

どうなんでしょう．少なくとも T1 エンコーディングの一覧表を見る限りでは良さそうに思うのですが……．

> 数式中の明示hbox

h-kitagawa@9f81b17b230c804267bd7de35a7cdabcf7643735 でやってみました．テストおねがいします．
（`\lastnodechar`でなく，`\ENC\x-y` の y の部分から `\xspcode` を取得するのが本筋，とコミットしてから気づきました）

**Comment by h-kitagawa** [comment]
ふと思ったのですが，pTeX (, LuaTeX-ja も) でシフト = 0 の hbox とそれ以外の hbox で \xkanjiskip の挿入処理を変えているのはなぜなのでしょう？

**Comment by zr-tex8r** [comment]
> 禁則パラメータ

デフォルトで入っていないのは、
「10年前は8ビットフォントエンコーディングの使用が一般的でなかった」
からで、単にそのまま放置されたのでしょう。
だから自分は `\xspcode=3` に変えてしまって構わないと思います。

※128～255の文字が何かはもちろんエンコーディングにより変わるわけですが、
よく使われるであろう、T1・LGR・T2Aを見比べる限りは、結局、
「全部3にする」が無難に思えます。

**Comment by aminophen** [comment]
> > 禁則パラメータ
>
> 「全部3にする」が無難に思えます。

ということであれば、ぜひ 128--255 の文字を `\xspcode=3` にしましょう。pLaTeX だけでなく pTeX のほうにも入れると consistent にできますね。

**Comment by aminophen** [comment]
> pTeX (, LuaTeX-ja も) でシフト = 0 の hbox とそれ以外の hbox で \xkanjiskip の挿入処理を変えているのはなぜなのでしょう？

確かに、「和欧文のバランス調節目的でシフトすると xkanjiskip が入らなくなる」だと嬉しくないですよね。なんでなんでしょう？（全然理解できないですが、ptexskip.pdf の 1.2 節って関係あります？）

**Comment by aminophen** [comment]
> > 数式中の明示hbox
> 
> h-kitagawa@9f81b17  でやってみました．テストおねがいします．

いま試してみたところ、大丈夫そうでした。

> 禁則パラメータ

kinsoku.tex の `\xspcode` の件は、次回にでも回そうと思います。とりあえずいまは従来のままにしておいて、新しく Issue #6 を立てます。この #5 のバグフィックスリリースを最優先します。

 # 変えた後に問題が起きるのはいやですし…

**Comment by zr-tex8r** [comment]
取りあえず「絶対にコケない `\pltx@isletter`」を実装してみました。

----

書式は `\pltx@isletter{<test>}{<true>}{<false>}` （現状と同じ）で、以下の仕様を満たす。

  * `<test>` を先頭完全展開した結果が単一の（カテゴリコード11または12の）欧文文字トークンであるかを判定する。
      * ただし誤って真と判定する例がある：`␣a{}` など。今回の目的には影響はない。
      * とにかく異常な動作を起こすのを避けるように努めた。
      * もちろん、 `<test>` を単独で実行した場合にエラーにならないことを仮定する。
  * 先頭完全展開可能。（つまり先頭展開を繰り返すと `<true>` か `<false>` の何れかに至る。）

```tex
\def\pltx@mark{\pltx@mark@}
\let\pltx@scanstop\relax
\long\def\pltx@cond#1\fi{%
  #1\expandafter\@firstoftwo\else\expandafter\@secondoftwo\fi}
\long\def\pltx@isletter#1{%
  \expandafter\pltx@isletter@i\romannumeral-`0#1\pltx@scanstop}
\long\def\pltx@isletter@i#1\pltx@scanstop{%
  \pltx@cond\ifx\pltx@mark#1\pltx@mark\fi{\@firstoftwo}%
    {\pltx@isletter@ii\pltx@scanstop#1\pltx@scanstop{}#1\pltx@mark}}
\long\def\pltx@isletter@ii#1\pltx@scanstop#{%
  \pltx@cond\ifx\pltx@mark#1\pltx@mark\fi%
    {\pltx@isletter@iii}{\pltx@isletter@iv}}
\long\def\pltx@isletter@iii#1\pltx@mark{\@secondoftwo}
\long\def\pltx@isletter@iv#1#2#3\pltx@mark{%
  \pltx@cond\ifx\pltx@mark#3\pltx@mark\fi{%
    \pltx@cond{\ifnum0\ifcat A\noexpand#21\fi\ifcat=\noexpand#21\fi>\z@}\fi
      {\@firstoftwo}{\@secondoftwo}%
  }{\@secondoftwo}}
```

**Comment by aminophen** [comment]
[forum:1941](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1941) の件、結構やっかいそうです… 新しく pLaTeX に入れた `\@text@composite` の引数の書式は ucsencs.def（や本家 LaTeX）の定義と inconsistent なのでエラーが出てしまいます。

~~~~
Runaway argument?
\ifx \uc@throw \undefined \else \def \uc@got {225}\uc@throw \global \let \ETC.
! File ended while scanning use of \@text@composite.
<inserted text> 
                \par 
~~~~

**Comment by zr-tex8r** [comment]
この `\@text@composite` のパラメタ書式が変わっているのって、ずっと疑問に思ってたんですけど・・・。

  * LaTeX オリジナル：`\def\@text@composite#1#2#3#{...}`
  * TL16 pLaTeX： `\def\@text@composite#1#2#3\@text@composite{...}`
  * `...` では `#3` は見ていない。
  * 標準LaTeXの範囲では呼出側は `\@text@composite \xxxx yy\@empty \@text@composite {\add@accent{NNN}{yy}}` のような形になる。
  * この条件の下だと、どちらのパラメタ書式にしても `#1` と `#2` は同じ。

結局、「変える必要は無い」ように見えるんですよね……。

**Comment by zr-tex8r** [comment]
ucsパッケージを読み込んだ場合は、
`\@text@composite {\xxxx}{yy}{\@empty}\@text@composite{\add@accent...}`
という形の呼び出しが起こるようです。
本来は`{\@empty}` の部分が“捨てられて”ほしいのですが、
TL16のpLaTeXの定義だと、`{\add@accent` の `{` じゃなくて `{\@empty` の `{` を拾ってしまいます。

**Comment by h-kitagawa** [comment]
パッチ書いたのは私 (http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1851#p10875) ですが，`\@text@composite` のパラメタ書式を変えた理由はよく覚えていません．間違った試行錯誤の結果だと思いますorz

LaTeX オリジナルから変えなくて（= pLaTeT での再定義を削除して）良いと思います．

**Comment by zr-tex8r** [comment]
> LaTeX オリジナルから変えなくて（= pLaTeT での再定義を削除して）良いと思います．

了解です。

h-kitagawa のほうのブランチのコードをチェックしてみましたが、問題なさそうです。

**Comment by aminophen** [comment]
h-kitagawa/master ブランチのコードから `\@text@composite` の定義を削除したものを aminophen/master ブランチに作ってみたところ、手元では ucs.sty も正しく動いているようです。platexrelease も込みでテストおねがいします。

**Comment by h-kitagawa** [comment]
aminophen@32b8de195a06addb0035bbb0cdf248bab8f9d98e を手元で試してみましたが，pLaTeX 上では platexrelease.sty, ucs.sty とも動いているようです．

upldefs.ltx を同等の内容で手動書き換えしてみましたが，upLaTeX 上で ucs.sty は動いている模様．upLaTeX 上の platexrelease は未検証です．

**Comment by aminophen** [comment]
> 取りあえず「絶対にコケない `\pltx@isletter`」を実装してみました。

これは入れたほうがよいのでしょうか？ いまのままでコケる例というのが全然わかっていなくてそのままにしているのですが。

**Comment by aminophen** [comment]
> upLaTeX 上の platexrelease は未検証です．

upLaTeX 上の platexrelease も大丈夫でした。（さきほどplatexrelease.dtx の version を上げ忘れたので aminophen@1962560 で上げなおしました）

ついでに #6 もやってしまおうかと思って考えているのですが、kinsoku.dtx を安直に platexrelease に乗せてしまうと upLaTeX がダメなことになる（pLaTeX と違って、upLaTeX の ukinsoku.tex は当初から 128--255 が `\xspcode=3` になっていた）ので、これは例外的に emulate の対象から外そうと思います。

 # まあ `\ifx\ucs\@undefined ... \fi` とか platexrelease.sty に書けば不可能ではないけれど…

**Comment by zr-tex8r** [comment]
> いまのままでコケる例

```latex
\documentclass{article}
\DeclareTextCompositeCommand{\^}{OT1}{?}{{hoge}}
\def\hoge{hoge}
\DeclareTextCompositeCommand{\^}{OT1}{!}{\hoge}
\begin{document}
\^? / \^!
\end{document}
```

**Comment by h-kitagawa** [comment]
（こんな場合まで対応する必要があるかわかりませんが）
aminophen@1962560337d093e4e01a1f2d566554ff0b77a794 では `\DeclareTextCompositeCommand{\"}{OT1}{圏}{テン}` のように和文に対してアクセントの合成方法を定義した場合に，`\"圏` 全体が欧文文字のように扱われてベースラインや `\xkanjiskip` の入り方がおかしくなります．

一応テストソースを．
```tex
%#!ptex2pdf -l a.tex
\documentclass{jarticle}
%\DeclareTextComposite{\"}{OT1}{圏}{`点}% invalid
\DeclareTextCompositeCommand{\"}{OT1}{圏}{テン}
\def\test{あ\AA あ\'eあ\'圏い\"圏うa\"圏a\AA a}
\begin{document}
\xkanjiskip10pt
\ybaselineshift10pt
\test\par
\ybaselineshift0pt
\test
\end{document}
```

**Comment by h-kitagawa** [comment]
> `\DeclareTextCompositeCommand{\"}{OT1}{圏}{テン}`
h-kitagawa@b1781d1cca304bf134c7f68d97ff058e3884bd9c で対応したつもりです．

**Comment by aminophen** [comment]
今まで出たテストケース（\xkanjiskip、カーニング・リガチャ、ucs.sty、コケる例、和文アクセント）は h-kitagawa@c785814 で通っているっぽいです。確認間違いや抜けがあったらすみません。

**Comment by aminophen** [comment]
h-kitagawa さんのブランチを texjporg に merge してリリース準備に移ろうと思います。併せて #6 も大丈夫だと思いますので、kinsoku ブランチの `\xspcode=3` も merge します。platex -> uplatex の sync も行いますので、日付は `pLaTeX2e <2016/06/10>` と `pLaTeX2e <2016/06/10u01>` とするつもりです。

**Comment by kmaed** [comment]
皆様，ありがとうございます．

* tests ディレクトリはリリース時に除外でよいですか？
* （uplatex の方の話ですが）バージョン番号の u01 というのはどのような規則でついているのでしょうか．

**Comment by aminophen** [comment]
ひとまず platex / uplatex を作業しました。ミスってないか確認していただけると助かります。

それと、#6 をマージしてから気づいたのですが：kinsoku.tex に `\@tempcnta` を使ったのが良くなかったと判断し、使わずに素直に書き直しました (259efd9) 。

**Comment by aminophen** [comment]
> （uplatex の方の話ですが）バージョン番号の u01 というのは

upLaTeX で動かない「pLaTeX 2.09 互換モード」に入るのを抑制したという些細なことです。勝手に入れてすみませんでした（[68f6f69](https://github.com/texjporg/uplatex/commit/68f6f699bd55c98f156719a097f2e6cf62b80734) に紛れたような格好で入っています）。

**Comment by h-kitagawa** [comment]
> tests ディレクトリ

除外して良いです．リポジトリにテストファイルがあると便利，というだけなので．

**Comment by aminophen** [comment]
もう少し書いておくと、p と up のバージョンについては私は以下の規則を考えています：

- upナントカ.dtx を pナントカ.dtx に追随させただけ → u** の数字はそのままに
- upナントカ.dtx 特有のコードを変更 → u** の数字を一つ増加させる

現在 uplatex.dtx と uplvers.dtx だけが、t-tk さんの「u00 パッチ」より進んでいるので「u01」を付けています。もし今後 pナントカ.dtx と独立に upナントカ.dtx を更新することがあれば「u02」とする、といった具合です。

**Comment by h-kitagawa** [comment]
> 数式中の明示hbox

もしや……と思い実験したところ，やはり `\mathsurround` が 0 pt でない場合を
考慮していませんでした．1時間以内に直します．

**Comment by aminophen** [comment]
`\mathsurround`、そんなのありましたね… ぜひ merge してください。

**Comment by aminophen** [comment]
> `\mathsurround`

merge ありがとうございます。uplatex にも commit しました。あとはリリースお願いします。

**Comment by kmaed** [comment]
> あとはリリースお願いします。

platex, uplatex の 2016-06-10 を CTAN にアップロードしました．

ptex-base の kinsoku も上げますか？

**Comment by aminophen** [comment]
> ptex-base の kinsoku

merge して上げていただけると助かります。ありがとうございます。

**Comment by h-kitagawa** [comment]
「MacTeX2016インストール後，TeX Live Utilityでアップデートすると コンパイルエラーが発生」http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1951 ですが，
```
\\OT1\'-i ->\@tabacckludge '\i
```
を先頭完全展開するともう一回 `\@text@composite` が出てくるのが原因のような気がします．

とりあえず，4a1013af447d813e80037cc02bf64f797931c0b1 で
`\romannumeral` トリックを外したところ，動いているようです．

**Comment by zr-tex8r** [comment]
`#あちゃあ`

先頭完全展開としている際に、先頭に if-トークンが現れてそれを展開してしまうと、
後ろに不均衡な `\else` や `\fi` が残ってしまって、それがエラーを起こしているようです。
「不均衡な条件トークン」自体は何とかして処理できたとしても、
「if-トークンの展開により条件ネストレベルが増えている」ことの対処は難しそうです。

>   4a1013af447d813e80037cc02bf64f797931c0b1 で \romannumeral トリックを外した

とりあえず、これが妥当そうです。

**Comment by kmaed** [comment]
修正がよさそうならリリースするのですが，バージョンはどうしましょうか．latex みたいに \ppatch@level を上げればよいのでしょうか．

**Comment by aminophen** [comment]
みなさまありがとうございます。ppatchlevel だけ上げると platexrelease 的にはコードがなかったことになるのですが、短期間での fix なのでそうしましょうか。

今から commit しますね。

**Comment by aminophen** [comment]
platex / uplatex とも大丈夫そうです。

**Comment by kmaed** [comment]
CTAN に上げました．

上の方で既に議論されているのかもしれませんが，\i の前後って OT1 だと xkanjiskip が入らないんですね．

**Comment by aminophen** [comment]
リリースありがとうございます。

> \i の前後って OT1 だと xkanjiskip が入らないんですね．

OT1 に限らず T1 でも入らないようですね。どうなんでしょう？ 一応、LaTeX2e svn r1195--1198 にかけて変わった OT1 の `\c{g}` も含めてテストソースを：
~~~~ tex
% pLaTeX2e <2016/06/10>+1 (based on LaTeX2e <2016/03/31> patch level 1)
\documentclass{jarticle}
\usepackage{fontenc}
% The line below is installed in LaTeX2e <2016/03/31> patch level 2 (2016-06-20)
%\DeclareTextCompositeCommand{\c}{OT1}{g}{\textcommaabove{g}}
\begin{document}

\fontencoding{OT1}\selectfont
あ\c{g}あ{\i}あ{\j}あ % LaTeX2e PL1 と PL2 の g のアクセントに注目

\fontencoding{T1}\selectfont
あ\c{g}あ{\i}あ{\j}あ

\end{document}
~~~~

**Comment by aminophen** [comment]
> OT1 の `\c{g}`

というか、そもそも `\textcommabelow` と `\textcommaabove` (Added 2015/02も `\AA` と似た構造なのでベースライン補正で乱れるのですね…
~~~~ tex
\documentclass{tarticle}
\begin{document}
あ\textcommaabove{g}あ % macro added in LaTeX2e 2016/02/01
あ\textcommabelow{n}あ % macro added in LaTeX2e 2015/10/01
\end{document}
~~~~

**Comment by h-kitagawa** [comment]
> `\textcommabelow`, `\textcommaabove`

latex.ltx の `\textcommabelow` の定義を見ると
```
\DeclareTextCommandDefault\textcommabelow[1]
  {\hmode@bgroup\ooalign{\null#1\crcr\hidewidth\raise-.31ex
   \hbox{\check@mathfonts\fontsize\ssf@size\z@
   \math@fontsfalse\selectfont,}\hidewidth}\egroup}
```
のように表組みで組まれているので，周囲に `\xkanjiskip` は入らないですね．
困った．

> `\i`, `\j`

これって単純に `\xspcode` が 0 になっているだけのような気がします．

**Comment by aminophen** [comment]
> > \i, \j
>
> これって単純に `\xspcode` が 0 になっているだけのような気がします．

はい、そうだと思います。これを kinsoku.tex で 3 にして問題が起きるのかどうか… これは jsclasses や uplatex でも `\xspcode` は 0 のままなので、この前の 128--255 より心配です。

**Comment by aminophen** [comment]
> > \i, \j
>
> これって単純に `\xspcode` が 0 になっているだけのような気がします．

> > というか、そもそも `\textcommabelow` と `\textcommaabove` も `\AA` と似た構造なので、縦組ではベースライン補正で乱れるのですね…
> 
> latex.ltx の `\textcommabelow` の定義を見ると [...] のように表組みで組まれているので，周囲に `\xkanjiskip` は入らないですね．困った．

さらに試すと：

- `\c{a}` は周囲に xkanjiskip が入らない
- `\d{a}` と `\b{a}` は周囲に xkanjiskip が入らない + ベースライン補正 ≠ 0 で乱れる

うまいやり方があれば別ですが、キリがないので昨日 CTAN リリースした状態で様子見ということでよいと思っています。

**Comment by aminophen** [comment]
いったん #9 で外した exppl2e.sty をテストしていて、LaTeX との挙動の違いを見つけました。
~~~~ tex
%\RequirePackage{exppl2e}
\documentclass{jarticle}
\begin{document}
あ$\AA$あ
\end{document}
~~~~
これは警告だけが出て、コンパイルは通ります。
~~~~
LaTeX Warning: Command \r invalid in math mode on input line 4.
~~~~
ところが、exppl2e を使うと、警告の後にさらにエラーが出て止まります。
~~~~
LaTeX Warning: Command \r invalid in math mode on input line 4.

! Missing \endgroup inserted.
<inserted text> 
                \endgroup 
l.4 あ$\AA
          $あ
~~~~

**Comment by h-kitagawa** [comment]
> 数式モード中の `\AA`

オリジナルの LaTeX で

```latex
\documentclass{article}
\begin{document}
$\'a$
\end{document}
```

を処理させた場合でも，次のようにエラーが出ます．

```
LaTeX Warning: Command \' invalid in math mode on input line 4.

! Please use \mathaccent for accents in math mode.
\add@accent ...@spacefactor \spacefactor }\accent 
                                                  #1 #2\egroup \spacefactor ...
l.4 $\'a
        $
? 
```

なので，`$\AA$` でエラーが発生しても私は不自然ではないと思っています（が，挙動が変わるという点では気になりますね）．

**Comment by aminophen** [comment]
> `$\AA$` でエラーが発生しても私は不自然ではないと思っています

今回のケースだと、`$\AA$` だけオリジナルの LaTeX が（出力が不正なのに）エラーを出さないのが不思議なのかもしれないです。`$\mbox{\AA}$` だと期待どおりの出力になるのに、警告だけだとその書き方へ導かれない気がします。

**Comment by aminophen** [comment]
そもそもオリジナルの LaTeX って、どうして `\r{A}` だけ ot1enc.def で（`\accent` を使わず `\char` を使って）特別に定義しなおしているのでしょう？
~~~~ tex
\DeclareTextCompositeCommand{\r}{OT1}{A}
   {\leavevmode\setbox\z@\hbox{!}\dimen@\ht\z@\advance\dimen@-1ex%
    \rlap{\raise.67\dimen@\hbox{\char23}}A}
~~~~
これさえなければ `$\AA$` は他のアクセント同様 `! Please use \mathaccent for accents in math mode.` のエラーを出しますし、pLaTeX の \xkanjiskip 的にも \tbaselineshift 的にも都合よいのに…

**Comment by aminophen** [comment]
アクセント文字パッチについて、まずそうな挙動を見つけました。

~~~~ tex
\RequirePackage{exppl2e}
\documentclass{jarticle}
\usepackage[czech]{babel}
\begin{document}
\ybaselineshift10pt
d\par
\v{d}\par
d\v{d}\par
\end{document}
~~~~

~~~~
! You can't use `\lower' in vertical mode.
<argument> ...neshift \z@ \\OT1\v-d }\else \lower 
                                                  \@tempdima \box \z@ \fi \f...
l.7 \v{d}
         \par
? 
~~~~

exppl2e を読み込んだ状態でのみエラーが出ます。

**Comment by h-kitagawa** [comment]
単純に {{{\lower}}} の前に {{{\leavevmode}}} を入れるとエラーはなくなります．
何か副作用がなければよいですが．

**Comment by aminophen** [comment]
a32defa で exppl2e.sty の `\@text@composite@x` に \leavevmode を足しました。

しばらくテストして様子をみましょう。

**Comment by aminophen** [comment]
LaTeX2e 2017/01/01/ Patch level 2 で、「アクセント文字パッチ」の命令群を呼び出す親命令 \DeclareTextCompositeCommand が微妙に修正されました（`\@empty` 追加）。TeX Live r43287 
で反映されていますので、多分大丈夫とは思いますがアップデートした状態でテストしたほうが無難そうですね。

**Comment by aminophen** [comment]
ものすごく日があいてしまいましたが，fixcompositeaccent ブランチを作り，

- デフォルトでは合成アクセントについて何もしない
- `\fixcompositeaccent` 命令が有効な範囲でのみ，合成アクセントを改善する

という仕様ならなんとかなるんじゃないかと考えて実装してみました。手元のテストケースは

- https://gist.github.com/aminophen/842a7188b922ae83a7190c4d571b18d7

に置いています（適宜 \documentclass を jarticle と tarticle に変えながら実験中）。コミット af2dbc2 までで，ほぼ全てのケースでうまくいっているのですが，

- ベースライン補正量が非ゼロのときだけ，`あ\c{g}あ` と `\textcommaabove{g}あ` の挙動が一致しない（前者は \xkanjiskip が入るべきところに入らない）

という問題が起きています。

**Comment by aminophen** [comment]
> `あ\c{g}あ` と `\textcommaabove{g}あ` の挙動が一致しない

→ 3d448f9 で解消。

**Comment by aminophen** [comment]
2018-07-28 リリースで \fixcompositeaccent / \nofixcompositeaccent 命令を追加しました。

ひとまず完了とします。
