### ISSUE TITLE
\inhibitglue の省略形 \<

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#50]
https://twitter.com/zr_tex8r/status/896321712664461312

https://twitter.com/zr_tex8r/status/896323051071037440

今の `\<` の定義（plfonts.dtx内）は

~~~~ tex
\def\<{\inhibitglue}
~~~~

ですが，[TeX Live 2014 での \inhibitglue の仕様変更](http://doratex.hatenablog.jp/entry/20140714/1405302796)により垂直モードで効かなくなったこと，および `\<` は「LaTeX 的な命令」であることから

~~~~ tex
\def\<{\leavevmode\inhibitglue}
~~~~

がいいのでは？という話はこちらで。

**Comment by zr-tex8r** [comment]
チョット試してみたのですが

```latex
\def\<{\leavevmode\inhibitglue}
```

これだと`\leavevmode`が`\inhibitglue`の前側の効力を妨げてしまうようです。

となると、

```latex
\def\<{\ifvmode\leavevmode\fi\inhibitglue}
```

ですが、これだと動く引数での挙動が心配です。結局

```latex
\DeclareRobustCommand*\<{\ifvmode\leavevmode\fi\inhibitglue}
```

でしょうか。

**Comment by aminophen** [comment]
どういうわけか

~~~~ tex
）\<\<（
~~~~

と書いた場合，従来の `\def\<{\inhibitglue}` だと両方のカッコのグルーが消えますが，これを robust にした場合や ZR さんご提案の定義にした場合に片方消えなくなりますね。なぜでしょう？

**Comment by abenori** [comment]
）\relax\inhibitglue（

とおなじ？

**Comment by h-kitagawa** [comment]
もはや LaTeX フォーマット自体が e-TeX 拡張を要求していることを考えると，
```tex
\protected\def\<{\ifvmode\leavevmode\fi\inhibitglue}
```
ではどうでしょうか？

**Comment by aminophen** [comment]
> ）\relax\inhibitglue（
> とおなじ？

納得しました。それでは，e-TeX の \protected を使うことにしましょう。

**Comment by aminophen** [comment]
cb41066 でカーネルに移しました。ただ texjporg/tex-jp-build#28 という話もあるので，しばらく open のままにしておきます。
