### ISSUE TITLE
新元号対応

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#64]
元号が変わるまで，残り一年とちょっとになりました。

＃ 気が早いかも？ … という気がしないでもないですが，5月1日は例年「TeX Live pretest 期間中」なので，一般向けのパッケージアップデートは降りてきません。そう考えると，仮に新元号対応するのであれば，本当のタイムリミットはもっと早く，あと約一年（cf. 今年の pretest は3月12日スタート）です。

今 texjporg が管理しているもので「平成」を使っているものは

- jclasses / ujclasses (platex / uplatex)
- jsclasses
- babel-japanese

があります。さて，どうしましょうか。

また，上に挙げたパッケージ以外に漏れがあったら指摘ください…というところなのですが，

- そもそも漏れを心配しないといけないことが面倒
- 全部同じように変更しないといけないのも面倒

なので，元号専用のパッケージを作ってしまうのも一つの手かと思います。ご意見を募ります。

**Comment by aminophen** [comment]
pLaTeX / upLaTeX の標準クラス群 (jclasses.dtx, ujclasses.dtx) の \today を，今夏中くらいにデフォルト \和暦 から \西暦 に変えておこうと思いますが，異論ありますでしょうか？

**Comment by aminophen** [comment]
2018-07-28 のリリース（クラスファイルの日付は 2018/07/03）で \today を西暦に変えました。

`\和暦` を今後どうするか（\heisei というカウンタ名はどうするか，もですね！）は要検討なので，まだ open なままにしておきます。

**Comment by h-kitagawa** [comment]
`\和暦` な場合を LuaTeX-ja の ltjclasses（コミット[その1](https://ja.osdn.net/projects/luatex-ja/scm/git/luatexja/commits/871900f0dca66ffbd2b0d6802c5d83a119b89448)，[その2](https://ja.osdn.net/projects/luatex-ja/scm/git/luatexja/commits/f295974dded4b22cfa6bc734353994c79e6b146b)）で試しているところです．

LaTeX の段階で e-TeX 拡張が前提になっているので，`\numexpr` を使えば，和暦出力自体には カウンタ `\heisei` を使う必要はないですね（どれだけ実際に使っている例があるのだろうか……）．

**Comment by aminophen** [comment]
\heisei は一応，公開カウンタなんですよね…。最も無難なのは

- 隠しカウンタ `\ja@year` を作っておき，後方互換性のため「\today が平成の範囲内であれば `\let\heisei\ja@year`」とする
- 令和 \reiwa は新設しない

でしょうか？ 仰る通り，カウンタを節約するなら \numexpr を使う手もありますね。

**Comment by h-kitagawa** [comment]
> \heisei は一応，公開カウンタ

残すのなら「何らかの意味」を持つ値にしたいという気持ちがあります．元号が決まる前に「平成36年」のような記法が存在したことを考えると，`\heisei=\numexpr\year-1988\relax` 固定とするというのはどうでしょうか．

> 令和 \reiwa は新設しない

私はこれに +1 です．

**Comment by aminophen** [comment]
あまり重要ではありませんが，そういえば最近は `SOURCE_DATE_EPOCH` + `FORCE_SOURCE_DATE` で \year が変わるんですよね。昭和な年はもうサポート外とする？

**Comment by h-kitagawa** [comment]
一応「`SOURCE_DATE_EPOCH` が (UTC) 1970-01-01 基準の秒数」ということを考えると，それを理由に「昭和までサポート」という基準にすることはできそうです．

----
なお，`SOURCE_DATE_EPOCH` には（少なくとも x86-64_linux では）絶対値の大きい負数を指定できます．
```
SOURCE_DATE_EPOCH=`echo '-(2^48)'| bc` FORCE_SOURCE_DATE=1 ptex '\message{\the\year, \the\month, \the\day}\end'
% ==> -8917617, 1, 25
```

**Comment by aminophen** [comment]
> \heisei=\numexpr\year-1988\relax 固定とする

では，そうすることにしましょうか。

> (UTC) 1970-01-01 基準の秒数

確かに「昭和までサポート」は合理的な理由がありますね。

**Comment by aminophen** [comment]
> 残すのなら「何らかの意味」を持つ値にしたい
> \heisei=\numexpr\year-1988\relax 固定とする

では，そうすることにしましょうか。

> (UTC) 1970-01-01 基準の秒数

確かに「昭和までサポート」は合理的な理由がありますね。

**Comment by h-kitagawa** [comment]
漢数字で出力するか否かの判定を `\iftdir` で行っているので，縦数式ディレクションでも `\today` の出力が「平成三一年四月二日」のように漢数字になりますが，こちらはどうしましょうか？

**Comment by aminophen** [comment]
> 縦数式ディレクション

確かに tabular 環境とかの z で \today を使う可能性は無いとはいえないですね。私は漢数字よりアラビア数字のほうが好みです。

**Comment by h-kitagawa** [comment]
https://github.com/texjporg/platex/commit/9f9116235cc83cb33fb2e7d4437ecbea06a4c9ce （まだ new_japanese_era_name ブランチ）で縦数式ディレクションのときには算用数字で出力するようにしました．

**Comment by aminophen** [comment]
> new_japanese_era_name ブランチ

ありがとうございます，良いと思います。今日か明日にはリリースしたいと思います。
