### ISSUE TITLE
縦組で「空のフロート」だけのページのフッター

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#78]
```` tex
\documentclass{tarticle}
\begin{document}
\begin{figure}
\end{figure}
\clearpage
a
\end{document}
````

このソースを（2017/01/01 以降〜最新までの LaTeX2e ベースの）pLaTeX で処理すると，1 ページ目が空っぽになりますが，フッターのページ番号が持ち上がります。

類似の「持ち上がる」問題には `\@makecol` の「縦組時は `\vbox{\hskip\z@}` を発生させる」という処理で対処してあったはずなのですが，なぜかこの時は効かないようです。

＃ 別に変な実験がしたかったわけではなく，前の #76 に関連してテスト中に

```` tex
\begin{figure}
\layoutfloat(180pt,300pt){一応，図です一応，図です一応，図です}
\end{figure}
````

という「\pcaption を忘れる」という単純ミスで図が消え飛んだ時に起こってびっくりした。

----

なお，このソースは LaTeX2e のバージョンによって挙動が違います。

- 巻き戻しなし 〜 \RequirePackage[2017/01/01]{latexrelease}
    → 空のページと「a」とだけ表示されたページの計2ページ
- \RequirePackage[2016/12/31]{latexrelease} 〜 \RequirePackage[2015/01/01]{latexrelease}
    → \clearpage のところでエラー `! Output loop---100 consecutive dead cycles.`
- \RequirePackage[2014/12/31]{latexrelease}
    → 「a」とだけ表示された1ページのみ

この違い自体は pdflatex などでも見られるので，今回の issue では取り扱いません。

**Comment by aminophen** [comment]
LaTeX2e 2020-10-01 にて ltoutput / ltshipout が改訂されるので，本件への対応も pLaTeX2e 2020-10-01 でカーネルに入れようと思います。

**Comment by h-kitagawa** [comment]
（`\begin{document}` の直後に組方向変更命令を入れて試したところ）`\iftdir\hskip\z@\fi` ではなくて `\unless\ifydir\hskip\z@\fi` (= `\ifydir\else...\fi`) の方が良いような気がしてきました．

**Comment by aminophen** [comment]
試してみると，確かにそのようです。（`\@makecol` の方は \iftdir ... \fi で良いらしい）

**Comment by aminophen** [comment]
Done (pLaTeX2e 2020-10-01).
