### ISSUE TITLE
LaTeX2e 2019-10-01 対応

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#85]
LaTeX2e 2019-10-01 release candidate ('develop' branch) について気づいた点を書いていくコーナーです。【このコメントは随時状況アップデートしていきます】

- 新しい utf8.def が完全に動作するには，
    - \ifincsname プリミティブが必要（→ texjporg/tex-jp-build#83 → r51624）
    - ptexenc で不正な UTF-8 入力が和文文字 0xA2AF (EUC) に化ける症状への対策も必要（→ texjporg/tex-jp-build#90 → r52071）
- latex3/latex2e@ea254ee にて，\DeclareErrorFont が改訂されている。pLaTeX の \DeclareErrorKanjiFont も更新が必要 → a9fa3a9

**Comment by aminophen** [comment]
pLaTeX の問題ではないですが，情報として。

- latex3/latex2e#109 により \InputIfFileExists などの定義が変わるので「filehook パッケージ」が要 update ですね。仮に update が間に合わないと，luatexja とか plautopatch にダメージです。

```
! Package filehook Error: Detected unknown definition of \InputIfFileExists.
Use the 'force' option of 'filehook' to overwrite it..
```

**Comment by aminophen** [comment]
> \DeclareErrorKanjiFont

\DeclareErrorFont の変更の意図を汲むと，\DeclareErrorKanjiFont も要修正ですね。

``` tex
\documentclass[12pt]{article}

% Emulate lgrenc.def until v0.13.1 (2015-12-07).
% Note: v0.13.3 (2019-07-09) dropped \DeclareErrorFont due to bug latex/4399.
%\usepackage[LGR,T1]{fontenc}
\DeclareFontEncoding{LGR}{}{}
\DeclareFontSubstitution{LGR}{cmr}{m}{n}
\DeclareErrorFont{LGR}{cmr}{m}{n}{10}

\makeatletter
\usepackage{etoolbox}
\AtEndPreamble{\PackageWarningNoLine{mine}{font size is \f@size}}
\makeatother

\begin{document}

some text

\end{document}
```

これは platex では `Package mine Warning: font size is 10.` ですが platex-dev (2019-10-01-pre2) では `Package mine Warning: font size is 12.` です。ところが

``` tex
\DeclareErrorKanjiFont{JY1}{mc}{m}{n}{8}
```

をプリアンブルに一行足してやると，どちらも `Package mine Warning: font size is 8.` になり，LaTeX の変更意図をキャンセルしてしまっています。後日対応します。

**Comment by aminophen** [comment]
つい先ほど

> Merge branch 'robustness' into develop (latex3/latex2e@cffc0dc)

で沢山のコマンドが robust になりました。これは要チェックです。

**Comment by aminophen** [comment]
沢山のコマンドが robust になった中で，pLaTeX カーネルが再定義しているものとして以下を見つけました。（github-robust-0123.lvt というテストファイルが用意されていたので，これを単純に pLaTeX で走らせて LaTeX との差分を見ただけ。）

* \AtBeginDvi
* \strut
* \underline
* \usefont

ただ，他に \DeclareMathSymbol など数式用コマンド定義のためのコマンドも改修されているので，[mathfam256 パッケージ](https://github.com/aminophen/mathfam256)も改修が必要となっておりこちらの方が面倒そう…。

**Comment by aminophen** [comment]
mathfam256 パッケージは https://github.com/aminophen/mathfam256/compare/8b6e255...d86b940 でなんとかなりました。（従来の LaTeX でもうまく動いていなかった部分があった…。）

pLaTeX カーネルの方は，上の4つも \DeclareRobustCommand に切り替えるつもりですが，この4つ以外にも今回の意図を汲み取ると他の pLaTeX 独自命令も robust にすべきものがありそうです。

**Comment by aminophen** [comment]
```
pLaTeX2e <2019-10-01>-pre-2
```

\AtBeginDvi, \strut, \underline, \usefont と \usekanji, \useroman は robust にしました。

**Comment by aminophen** [comment]
[luatexja](https://ja.osdn.net/projects/luatex-ja/scm/git/luatexja/commits/2df1699c04b21d9e6481c37338ce5efb856bd369) を見て，たしかにと思ったので \tstrut, \zstrut, \ystrut も robust にしました。

----

さて，pLaTeX が追加している「ユーザ用命令」には以下のものもあります：

- \adjustbaseline
- \userelfont

他に plext のこの辺も気になっています：

- \bou
- \kasen

これらも robust にしようかと考え中。

**Comment by h-kitagawa** [comment]
> \adjustbaseline, \userelfont, \bou, \kasen

とりあえず LuaTeX-ja では robust にしておきました．
他にないかなあ，というのと．エンジンレベルの \protected を使わない利点は何か，というのが気になっているところです．

**Comment by aminophen** [comment]
> \adjustbaseline, \userelfont, \bou, \kasen

platex でも robust にしました。「他にないかなあ」は十分調べられていません…。

**Comment by aminophen** [comment]
ひとまず LaTeX2e 2019-10-01 が出たらその日じゅうに pLaTeX2e 2019-10-01 として出そうと考えています。upLaTeX の方も同日に出します。

**Comment by aminophen** [comment]
https://github.com/latex3/latex2e/releases/tag/release-2019-10-01

LaTeX2e 2019-10-01 が出ました。本日帰宅次第，pLaTeX2e 2019-10-01 を出します。

**Comment by aminophen** [comment]
classes.dtx が更新されているのを忘れていました。\normalsize, \Large などフォントサイズ変更命令や \title 系命令が robust になっているので，追随しようと思います。

**Comment by aminophen** [comment]
texjporg/platex@dd53826 と texjporg/uplatex@c5969bc で jclasses.dtx と ujclasses.dtx を更新しました。（リリースは他の案件が出てくるまで待とうと思っていますが）

**Comment by aminophen** [comment]
他の案件が出てきてしまった… → 2cb7ea6 ので，これが正常動作していれば pLaTeX2e 2019-10-01 patch level 1 としてリリースしようと思います。
