### ISSUE TITLE
stable / unstable?

### ISSUE THREAD

**Issue by aminophen** [texjporg/platex#9]
[forum:1954](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1954) の kmaed さんの

> stable/unstable の区分があればよいのですが……．分けても unstable を試す人が少なくてあんまり意味ないのかな．

をみて、ものは試しということで exppl2e.sty を作ってみました。[forum:1956](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1956) の ZR さんの `\AtBeginDvi` をとりあえず入れてあります。

カーネル開発の理想としては最終的に exppl2e.sty から plﾅﾝﾄｶ.dtx にコードをインポートしたいですので、sty 単独でもコンパイルが通るようにしてみました。ご意見よろしくお願いいたします。

**Comment by h-kitagawa** [comment]
[forum:1958](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1958) への

> 現在のエンコーディング（\f@encoding）が〝PD1”であるかを調べる

という対応を h-kitagawa@4d2305f5df0d507c3a2d34b77b75aa4fb7ea7bb4 に入れました．

**Comment by aminophen** [comment]
> h-kitagawa@4d2305f

これは動いているようにみえます。が、どうしたものですかね… いまトラブル(?)が相次いでいるのは「アクセント文字パッチ」だけですので、いったん plfonts.dtx から丸ごと外して experimental に（あるいは unstable に）移してしまったほうがよいのかもしれません。どう思われますか？

**Comment by h-kitagawa** [comment]
> いまトラブル(?)が相次いでいるのは「アクセント文字パッチ」だけですので、いったん plfonts.dtx から丸ごと外して experimental に（あるいは unstable に）移してしまったほうがよいのかもしれません。

たしかにそうですね．私はありかと．（その方が LuaTeX-ja 側も頻繁な更新がなくなる，というのもあります）

**Comment by aminophen** [comment]
> plfonts.dtx から丸ごと外して

外すといっても今回の「外す」は platexrelease タグ付けが相当難易度が高いので、いったん外し方も考えてみます。できなければそもそも外せないので…

**Comment by aminophen** [comment]
中間報告：いったん aminophen@d0fd524 で platexrelease guard をセパレートすることに成功した気がします。pldefs.ltx はこのコミットで diff が皆無ですし、platexrelease.sty も同じ機能を果たしてくれるようにみえます。あとは「外す」ですね。

**Comment by aminophen** [comment]
aminophen@fe68136 で外してみたところ、なんとかなりました。外した分のコードは exppl2e.sty に移してあります。あとは、外すかどうか自体についてのご議論よろしくお願いいたします。

**Comment by abenori** [comment]
> 最終的に exppl2e.sty から plﾅﾝﾄｶ.dtx にコードをインポートしたい

これはどういう形になるんでしょう？

**Comment by aminophen** [comment]
> > 最終的に exppl2e.sty から plﾅﾝﾄｶ.dtx にコードをインポートしたい
> 
> これはどういう形になるんでしょう？

単純なカット＆ペーストを想定しています。platex → uplatex の sync も簡単になるかなと。今まで sync は私がリリース直前の最終局面で

+ `git diff 前回リリースタグ 今回リリース予定タグ > patch.txt`
+ patch.txt を編集して .dtx の変更部分だけ残し、ヘッダ部を plﾅﾝﾄｶ.dtx から uplﾅﾝﾄｶ.dtx に修正
+ `iconv -f ISO-2022-JP -t UTF-8 patch.txt > patch-8.txt`
+ uplatex のディレクトリで `patch -p0 <patch-8.txt`
+ reject された部分（ほとんどが `\CheckSum` とバージョン番号のところ）を手動で書き直す
+ `make` で ltx などを作る

としていました。1. + 2. にあたるものが exppl2e.sty にあると考えれば、だいぶ楽です。

**Comment by aminophen** [comment]
[forum:1956](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1956) の ZR さんの `\AtBeginDvi` が割と critical なのと、[forum:1958](http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1958) の PDF しおりの件もありますので、あまり時間をかけずに一旦リリースを行いたいと思います。`\AtBeginDvi` は lltjp-geometry.sty などでも実績がありますから、もう安全とみなせると私は考えています。

stable / unstable (or, experimental) の区別をハッキリさせることそのものは大体合意しているとみなしますと、論点は以下の 2 点でしょうか：

- stable / unstable をどう実装するか。
    - 案 1：デフォルトは stable で、実験したい人はそのときだけ exppl2e.sty を `\RequirePackage` する（現在の h-kitagawa ブランチ）。フォーマット作成不要だが、テスト回数の絶対値が減りそう。
    - 案 2：デフォルトは stable で、実験したい人は exppl2e.ltx も含めてフォーマットにダンプする（exppl2e を sty 形式から ltx 形式に書き換え、フォーマット化するかどうか選べる仕組みを入れる）。フォーマット化しておくことで、テスト回数の絶対値は増えそう。
    - 案 3：現状維持。デフォルトは unstable で、不都合があったらユーザに platexrelease を使ってもらう。デフォルト化されているのでバグレポートは高速化するが、迷惑もかかりやすい。
- トラブル続きの「アクセント文字パッチ」を一旦外す（stable → unstable へ移す）か否か。
    - h-kitagawa ブランチでは既に unstable へ移転済み。

私自身は論点 1 で「案 1」、論点 2 で「外す」を支持します。もし他の案があれば追加してください。

**Comment by aminophen** [comment]
論点 1

> stable / unstable をどう実装するか。

について、案 1 と案 2 のいいとこ取りな「フォーマット作成の知識がある人はフォーマット化で、そうでないもしくは作成が面倒な場合は `\RequirePackage` で」と選べる方法も実装してみました。aminophen/expformat ブランチです。こちらを案 4 とします。

**Comment by h-kitagawa** [comment]
論点 1
> stable / unstable をどう実装するか。

デフォルトは stable でいいと思いますが，テスト回数が減ってしまうのはやはり気になります．
案をやたら増やすのは考えものですが，h-kitagawa/platexcfg ブランチで次の案を提案します．

 * 案5: 「platex 起動時に platex.cfg が存在すればそれを読み込む」コードを新設
   * テストしたい，という人は，`\RequirePackage{exppl2e}` という内容の platex.cfg を置くだけで済むはずです．
   * 現状では単に \input するだけなので，なんでも書けてしまうのが個人的には不安なところ．

論点2
> トラブル続きの「アクセント文字パッチ」を一旦外す（stable → unstable へ移す）か否か。 

「unstable へ移す」に一票．

**Comment by aminophen** [comment]
> h-kitagawa/platexcfg ブランチで次の案を提案します．

ありがとうございます。案 5 は stable/unstable 切替えにフォーマットを再作成しなくてよいところがいいですね。テストしたい、という場合にも

- TEXMF/tex 以下に `\RequirePackage{exppl2e}` という内容の platex.cfg を用意する
- （platex.cfg を用意せずに）ソース中に `\RequirePackage{exppl2e}` と書く

の 2 通りから選べます。

> 現状では単に \input するだけなので，なんでも書けてしまうのが個人的には不安なところ．

さすがに悪意あるコードを platex.cfg に書いて CTAN で配布してくるようなケースはないと思いますが… この不安さえ解消すればいちばん支持しやすいかもしれません。

 # 本筋とは外れますが、Makefile にワイルドカードで `rm *.cfg` としているのを、仮に案 4 または案 5 が採用された場合には直すことにします（備忘録のつもり）。

**Comment by zr-tex8r** [comment]
私は次のものを指示します。

  * 論点1では「案5」
  * 論点2では「unstableへ移す」

「platex.cfgに何でも書ける」という点については、
「今のpLaTeXの機構だと悪意のある人は結局（TeX言語コードなら）何でも書ける」
のでそんなに問題ではないかと。
ただし、「platex.cfg読込時の端末表示」はもっと派手にしたほうがいいかも知れません。

```
*************************
* Loading platex.cfg.
*************************
```

ところで：
“exppl2e”という名前はもうチョット解りやすいものの方がいいのかも。
“expl-platex”とか。
（“fixltx2e”はまだ「8文字以内」で名づけようとしていた頃の名残でしょう。）

**Comment by aminophen** [comment]
> “expl-platex”とか。

exppl2e という名前は fixltx2e と expl3 をかけあわせたつもりでしたが、不評ならそっちに変えます。

**Comment by munepi** [comment]
* 論点1：案5
 * 論点2：unstable へ移す

[64eec8e](https://github.com/h-kitagawa/platex/commit/64eec8e404eb4759ff011bd7503c1f0e43ff416d) を見ますと、`platex.cfg` を単に `\input` しているだけですから、あるissueをテストするためのディレクトリ直下に `platex.cfg` を置いても良いですね。

**Comment by aminophen** [comment]
> あるissueをテストするためのディレクトリ直下に platex.cfg を置いても良いですね。

そうですね。h-kitagawa さんが tests/ 以下に platex.cfg を置いてくださっていますし。tests/ のテストケースも、今後増やしていきましょう。

**Comment by aminophen** [comment]
> ただし、「platex.cfg読込時の端末表示」はもっと派手にしたほうがいいかも知れません。

aminophen/platexcfg で派手にしてみました。

**Comment by aminophen** [comment]
論点 2

> トラブル続きの「アクセント文字パッチ」を一旦外す（stable → unstable へ移す）か否か。

みなさまありがとうございます。unstable へ移す変更を、texjporg/master に push しました。

論点 1

> stable / unstable をどう実装するか。

支持が高かった案 5 を merge しようと思います。これにあわせて、いったん platex → uplatex sync をかけますが、念のため：upLaTeX のほうは platex.cfg ではなく uplatex.cfg としておきますね。

そうしますと、あとは以下が残っているようです：

- `\AtBeginDvi` のパッチを unstable → stable に移すか否か。
- exppl2e という名前を exp-platex に変えるか。

**Comment by aminophen** [comment]
> `\AtBeginDvi` のパッチを unstable → stable に移すか否か。

いまのままだと color / graphics の dvips.def が縦組で使えないままになってしまいますので、stable に移しました。フォーマット日付は platex / uplatex ともに 2016/07/01 です。

> exppl2e という名前を exp-platex に変えるか。

texjporg/master ブランチは exppl2e のまま、aminophen/platexcfg ブランチは exp-platex に変えたものを置きました。あとはお任せします。

----

さて：

> どこまでコミュニティ版 pLaTeX での改変を許容するのか

> 「LaTeX カーネルと同じ基準にする」

> リリースされるものとまんま同じ物が試せる

など、いただいたご意見に回答しないまま commit を進める結果になったことを申し訳なく思っております。「もっとバグを出さない努力」以前の問題で、「既に判明したバグの影響を最小限に抑えたい」がゆえに、stable のリリースを急いだ次第です。

テストの方法など、ほんとうはもっと良い方法があるのかもしれません。当面は stable にバグが出ないことを祈りつつ、ゆっくり議論させていただければ幸いです。「集い」の場もありますし。

さて、kmaed さんにリリースをおまかせしてよろしいでしょうか。（← このこと自体も、ほんとうは議論の対象にすべきなのかもしれません。）

**Comment by aminophen** [comment]
あっ、exppl2e.sty を（generated でない）source code 側に残す変更を create_archive.sh に入れるのを忘れていたことに今さら気づきました。ていうかもうリリース出ちゃっていますね。すみません

**Comment by kmaed** [comment]
> exppl2e.sty を（generated でない）source code 側に残す変更

ちゃんとチェックしなかった私のせいです．ごめんなさい．CTAN に上げちゃっていたのですが，反映されるまでにはまだ間に合いそうなので上げ直しました．早めにお知らせいただきありがとうございました．他にも何かミスがあれば教えて下さい．

.tds.zip については，同じファイルが source/ と tex/ の両方にあるのも妙かと思って，tex/ 以下にだけ入れてあります．doc/ 以下の source でもあるのですが，前例がないようでどうするのが正しいのかよくわからないです．

exppl2e.sty の名前については，expl3.sty もあるしいいんじゃないかなあ，と個人的には思っています．

**Comment by aminophen** [comment]
お手数おかけしました。やっと plnewsc03.tex も作りましたので（これを CTAN に入れなおす必要はないです）、明日にでも 2016-07-01 が TeX Live に入ったことを確認してから forum にアップします。

CTAN の仕組みや .tds.zip など全然わかっていないのでまた今度教えてください。
